version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - grid
  firefox:
    image: selenium/node-firefox
    restart: always
    depends_on:
      - hub
    networks:
      - grid
    environment:
      HUB_HOST: hub
  chrome:
    image: selenium/node-chrome
    restart: always
    depends_on:
      - hub
    networks:
      - grid
    environment:
      HUB_HOST: hub
networks:
  grid: